# Generated by Django 2.1.4 on 2019-03-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice_again', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterlist',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
