# Generated by Django 2.1.4 on 2019-03-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice_again', '0002_auto_20190303_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
