# Generated by Django 2.1.4 on 2019-03-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice_again', '0003_auto_20190304_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterlist',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='voterlist',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='voterlist',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='voterlist',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='voterlist',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
